1 -> f, x, z
2 -> hl, pw
3 -> anz, lab, xcr, yfn, ztw
4 -> bhol, dcos, gvri, lnqw
5 -> bxros, mlsuy, pucrf, tgcwe, uynti, xvmft
6 -> bsxnqd, ubdofz
7 -> ebkxaqm, zygcpxh
8 -> dqjsriht, furgibvs, oydntwae, ypdoejks
9 -> hmyciukvb, spuzkvdah, uczkfqdve, vchmyuqbp
11 -> kowyegmsihl, wkhbqlatdex
12 -> hgrfewbctmnv, oxpgsivqrlmj, wnxdsuepbvia
13 -> dmwpohciqlatf, erkjdctoqglpb, pqycrviultoek, xvijrlcgdmopf
14 -> aqgmsuziyxpdtj, feralzuowhpcxq, gjeabyqkocsixv, seztmhqnpkgfur, tkzladgrfvhpsw
15 -> dzqlxmhfkpbvgua, ihlsnoxfzywvarg, rdfaypquviwgtsc, vxnjwmpoahzludq