1 -> a, v
2 -> dj, qs, ul, wv, yg
3 -> pco
4 -> fhpu, hixg, lpyr, uiea, yjlc
5 -> gbqij, goful, lhpcy
6 -> coepsl, feryju, lnzjvo, owialx, rnogcb, vtyick
7 -> bdgtvrw, fbtmivc, hytpigj, lsgterh, lwzprie, mguztlp, pmwzits, psuxavl
8 -> pgbxrwun
9 -> fuhmneizj, lfhgodvwq, lrfisqgyu, qdoznhyul, qgtkipfdh, ugjhxnzfq, uwqsdnhvk, yfgrdaozp, ynwqkfgtj
10 -> qizutanpgf, rsvlaxkfen
11 -> dhskgbrwfpc, dtnbjaemzxk, fhqutmbcogy, gmfbakdhrxv, kmvdjwzuygr, tuirfkoplbn, uyxfrzohkai, yjfelwdspmc, zxtkhrmpgiu
12 -> embokhvsxpjd, gzawytcijpem, idwayrplkuen, jhnfstmvgxiy, maoprjbivlgz
13 -> ipbxoretdsvcy, strhfulywjegn, vmjfrlagyetcd
14 -> jpsrtlbimxgevz, nzckjdimsbptyq, oipmeqdcgsbxfn, ovzlkfxqagmewn, yuvfgwpxoraetl
15 -> aoglcdnuqvswbxm, azjvrtnqsdmfluy, bvitgrejnklxopa, jibdxnolfpygtch
16 -> fbvpohzurasqcdwl
17 -> arsmkzydnhflqijgt, lpeyntxmagdqucfbh, zukayjlnspqbdvgfx
18 -> haitsrdqfzukopcwjx, hcnpywxvtzqldkioab, lmsvucjqthgzfdneix, ztwahcijuvnqyoplgr
19 -> kiptxcorheasjfwbnzg, kzowibjmtrvndcqfyhu, mtdvejxbrluagzcsnoh
20 -> enwxhblfcrkduzmsjpto, kbjlhqaxrswpenfvyimz, kznhdjymwgvxtqfolbrp
21 -> arvfpgjncolyzbxhiqdku, nwdmrapihkoytuqxbczev, uhcvzmtwiprxbgeqjofnl, uqbmlpizorfkdhyntajgx, vaqmohyerxtlibjfwzdpk
22 -> mbrpxuochlvwqjakydszfg, rfuavdoqxgjsbpmzhenitl
23 -> kzowrmexusdvynfiahgbcpl, wyikvqtrhzlcpnujagdombf
24 -> gltmwavcksqhpzfejnoribyd, xozjihwmgqyctulsnvpkfreb
25 -> golyibvnjexqthcukrpafmzwd, nqjhrtlyaxoukgvescmpibwfd, yuzbqwvxckjernpisoaftlhgm, ziclgeywfmqhsxvpborunjtda
26 -> ghuspnjvfcqldiotwmkzayxber, iqoezkfucwvgxpbsylahjrmntd, wjtpgaexufkvihyqmrobzdsnlc